# Uncomment this line to define a global platform for your project
platform :ios, '9.3'

target 'ShipwrecksObjc' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for LifepathPico
    pod 'AFNetworking', '~> 3.0'
    pod 'Mantle'
    pod 'SAMKeychain'
    pod 'IQKeyboardManager', '~> 4.0'
    pod 'Masonry'
    pod 'ASIHTTPRequest'
end
